config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  root "static_pages#home"
  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks#create"}
  mount Ckeditor::Engine => "/ckeditor"
  resources :reviews do
    resources :comments
    resource :like
  end
  namespace :admin do
    root "users#index", path: "/"
    resources :users, only: [:index, :show, :destroy]
  end
  resources :tours, only: [:index, :show]
  resources :book_tours
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize user
    user ||= User.new
    if user.is_admin?
      can :manage, :all
    else
      can :read, Tour
      can [:create, :update, :read], User
      can :manage, Review
    end
  end
end

app/models/activity.rb
class Activity < ApplicationRecord
  belongs_to :user

  validates :behavior, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/average_cache.rb
class AverageCache < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true
end

app/models/bank_account.rb
class BankAccount < ApplicationRecord
end

app/models/book_tour.rb
class BookTour < ApplicationRecord
  belongs_to :user
  belongs_to :tour

  has_one :card
  accepts_nested_attributes_for :card

  validates :people_number, presence: true

  def paypal_url(return_path)
    values = {
      business: Settings.business,
      cmd: "_xclick",
      upload: 1,
      return: "#{Rails.application.secrets.app_host}#{return_path}",
      invoice: id,
      amount: people_number * tour.price,
      quantity: "1",
      notify_url: "#{Rails.application.secrets.app_host}/update"
    }
   "#{Rails.application.secrets.paypal_host}/cgi-bin/webscr?" +
     values.to_query
  end
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :book_tour
  has_one :card_transaction

  attr_accessor :card_number, :card_verification

  before_create :validate_card

  def purchase
    response = GATEWAY.purchase price_in_cents, credit_card, purchase_options
    create_card_transaction(action: "purchase",
      amount: price_in_cents, response: response)
    book_tour.update_attribute(:purchased_at, Time.now) if response.success?
    response.success?
  end

  def price_in_cents
    (book_tour.people_number * book_tour.tour.price * 100).round
  end

  private

  def purchase_options
    {
      ip: ip_address,
      billing_address: {
        name: Settings.name,
        address1: Settings.address,
        city: Settings.city,
        state: Settings.state,
        country: Settings.country,
        zip: Settings.zip
      }
    }
  end

  def validate_card
    unless credit_card.valid?
      credit_card.errors.full_messages.each do |message|
        errors.add :base, message
      end
    end
  end

  def credit_card
    @credit_card ||= ActiveMerchant::Billing::CreditCard.new(
      type: card_type,
      number: card_number,
      verification_value: card_verification,
      month: card_expires_on.month,
      year: card_expires_on.year,
      first_name: first_name,
      last_name: last_name
    )
  end
end

app/models/card_transaction.rb
class CardTransaction < ApplicationRecord
  belongs_to :card
  serialize :params

  def response= response
    self.success = response.success?
    self.authorization = response.authorization
    self.message = response.message
    self.params = response.params
  rescue ActiveMerchant::ActiveMerchantError => e
    self.success = false
    self.authorization = nil
    self.message = e.message
    self.params = {}
  end
end

app/models/category_review.rb
class CategoryReview < ApplicationRecord
  include CustomOrder
  has_many :reviews, dependent: :destroy

  validates :title, presence: true
end

app/models/category_tour.rb
class CategoryTour < ApplicationRecord
  has_many :tours, dependent: :destroy

  validates :title, presence: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  include CustomOrder
  belongs_to :user
  belongs_to :review

  validates :content, presence: true
end

app/models/images_tour.rb
class ImagesTour < ApplicationRecord
  belongs_to :tour

  has_attached_file :image, styles: {small: "64x64", med: "100x100", large: "200x200"}
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :review
end

app/models/overall_average.rb
class OverallAverage < ActiveRecord::Base
  belongs_to :rateable, :polymorphic => true
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, class_name: "User"
  belongs_to :rateable, polymorphic: true

  #attr_accessible :rate, :dimension

end

app/models/rating.rb
class Rating < ApplicationRecord
  belongs_to :user
  belongs_to :tour
end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

app/models/review.rb
class Review < ApplicationRecord
  include CustomOrder
  belongs_to :user
  belongs_to :category_review

  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  validates :title, presence: true, length: {maximum: 100}
  validates :content, presence: true

  has_attached_file :image, styles: {small: "64x64", med: "100x100", large: "300x300"}
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/tour.rb
class Tour < ApplicationRecord
  ratyrate_rateable "rating"
  belongs_to :category_tour

  has_many :book_tours
  has_many :ratings, dependent: :destroy
  has_many :images_tours, dependent: :destroy

  scope :recent, ->{order created_at: :desc}

  validates :name, presence: true, length: {maximum: 100}
  validates :schedule, presence: true
  validates :place_departure, presence: true
  validates :time, presence: true
  validates :people_number, presence: true
  validates :transport, presence: true
  validates :price, presence: true
  validates :content, presence: true
  validates :time_start, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  ratyrate_rater
  devise :database_authenticatable, :registerable,
    :rememberable, :validatable, :omniauthable, omniauth_providers: [:facebook]

  has_many :book_tours
  has_many :likes, dependent: :destroy
  has_many :activities, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :ratings, dependent: :destroy
  has_many :reviews, dependent: :destroy

  def likes? review
    review.likes.where(user_id: id).any?
  end

  class << self
    def from_omniauth access_token
      data = access_token.info
      user = User.find_by email: data["email"]
      unless user
        password = Devise.friendly_token[0,20]
        user = User.create name: data["name"], email: data["email"],
          password: password, password_confirmation: password
      end
      user
    end
  end
  mount_uploader :avatar, AvatarUploader

  scope :alphabet, ->{order :name}

  def is_user? user
    user == self
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :load_review
  before_action :load_comment, except: :create

  def index
    @comments = Comment.latest.paginate page: params[:page],
      per_page: Settings.per_page
  end

  def create
    @comment = @review.comments.create comment_params
    if @comment.save
      respond_to do |format|
        format.html do
          flash[:success] = t "comment.added"
          redirect_to @review
        end
        format.js
      end
    end
  end

  def edit
    respond_to do |format|
      format.js
    end
  end

  def update
    @comment.update_attributes comment_params
    respond_to do |format|
      format.js
    end
  end

  def destroy
    if @comment.destroy
      respond_to do |format|
        format.html do
          flash[:success] = t "comment.deleted"
          redirect_to @review
        end
        format.js
      end
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:content).merge! user_id: current_user.id
  end

  def load_review
    @review = Review.find_by id: params[:review_id]
    unless @review
      flash[:danger] = t "review.not_found"
      redirect_to root_path
    end
  end

  def load_comment
    @comment = Comment.find_by id: params[:id]
    unless @comment
      flash[:danger] = t "comment.not_found"
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def logged_in?
    current_user.present?
  end

  def verify_admin
    unless current_user.is_admin?
      redirect_to root_url
    end
  end
end

app/views/comments/_comment.html.erb
<div id="comment-<%= comment.id %>">
  <div class="code-in">
    <p class="smith"><a href="#"><i class="glyphicon glyphicon-user">
      </i> <%= comment.user.name %></a>
      <span class="date">
        <%= time_ago_in_words(comment.created_at) %><%= t "ago" %>
      </span>
    </p>
    <div class="clearfix"> </div>
  </div>
  <div class="media-left">
    <a href="#">
      <img src="images/g1.jpg" alt="">
    </a>
  </div>
  <div class="media-body">
    <p><%= comment.content %></p>
  </div>
  <div >
    <% if current_user == comment.user %>
      <%= link_to "", edit_review_comment_path(comment.review, comment),
        class: "glyphicon glyphicon-edit", id: "comment-#{comment.id}", remote: true %>
      <%= link_to "", review_comment_path(comment.review, comment), method: :delete,
        data: {confirm: t("confirm_delete")}, class: "glyphicon glyphicon-trash text-danger",
         remote: true %>
    <% end %>
  </div>
  <hr />
</div>

app/views/comments/_edit.html.erb
<div>
  <%= form_for [@comment.review, @comment], remote: true do |f| %>
    <div id="comment_form">
      <div class="field">
        <%= f.text_area :content , class: "form-control reset-input" %>
      </div>
      <div class="actions">
        <%= f.submit t "submit" %>
      </div>
    </div>
  <% end %>
</div>

app/views/comments/_form.html.erb
<% if user_signed_in? %>
  <h3><%= t "comment.add_new" %></h3>
  <%= form_for [@review, @review.comments.build], remote: true do |f| %>
    <p><%= f.text_area :content, placeholder: t("comment.placeholder"), class: "form-control" %></p>
    <p> <%= f.submit t("submit"), class: "btn btn-primary" %></p>
  <% end %>
<% end %>

app/views/comments/create.js.erb
var comments_list = $('#comments-list');
comments_list.prepend('<%= j render @comment %>');
comments_list.find('div:last-child').addClass('last-comment');
$('#comment-form').html('<%= j render 'comments/form' %>');
$('#comment_content').val('');

app/views/comments/destroy.js.erb
$('#comments-list').html('<%= j render @review.comments %>');

app/views/comments/edit.js.erb
$('#comment-<%= @comment.id%>').click(function(){
  $('#comment-form').
    replaceWith('<%= j render "comments/edit", comment: @comment %>');
  })

app/views/comments/update.js.erb
var element = document.getElementById('<%= @comment.id %>');
element.remove();
$('#comments-list').prepend('<%= j render @comment %>');
$('#comment-form').html('<%= j render 'comments/form' %>');
$('.reset-input').val('');