config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  root "static_pages#home"
  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks#create"}
  mount Ckeditor::Engine => "/ckeditor"
  resources :reviews do
    resources :comments
    resource :like
  end
  namespace :admin do
    root "users#index", path: "/"
    resources :users, only: [:index, :show, :destroy]
  end
  resources :tours, only: [:index, :show]
  resources :book_tours
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize user
    user ||= User.new
    if user.is_admin?
      can :manage, :all
    else
      can :read, Tour
      can [:create, :update, :read], User
      can :manage, Review
    end
  end
end

app/models/activity.rb
class Activity < ApplicationRecord
  belongs_to :user

  validates :behavior, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/average_cache.rb
class AverageCache < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true
end

app/models/bank_account.rb
class BankAccount < ApplicationRecord
end

app/models/book_tour.rb
class BookTour < ApplicationRecord
  belongs_to :user
  belongs_to :tour

  has_one :card
  accepts_nested_attributes_for :card

  validates :people_number, presence: true

  def paypal_url(return_path)
    values = {
      business: Settings.business,
      cmd: "_xclick",
      upload: 1,
      return: "#{Rails.application.secrets.app_host}#{return_path}",
      invoice: id,
      amount: people_number * tour.price,
      quantity: "1",
      notify_url: "#{Rails.application.secrets.app_host}/update"
    }
   "#{Rails.application.secrets.paypal_host}/cgi-bin/webscr?" +
     values.to_query
  end
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :book_tour
  has_one :card_transaction

  attr_accessor :card_number, :card_verification

  before_create :validate_card

  def purchase
    response = GATEWAY.purchase price_in_cents, credit_card, purchase_options
    create_card_transaction(action: "purchase",
      amount: price_in_cents, response: response)
    book_tour.update_attribute(:purchased_at, Time.now) if response.success?
    response.success?
  end

  def price_in_cents
    (book_tour.people_number * book_tour.tour.price * 100).round
  end

  private

  def purchase_options
    {
      ip: ip_address,
      billing_address: {
        name: Settings.name,
        address1: Settings.address,
        city: Settings.city,
        state: Settings.state,
        country: Settings.country,
        zip: Settings.zip
      }
    }
  end

  def validate_card
    unless credit_card.valid?
      credit_card.errors.full_messages.each do |message|
        errors.add :base, message
      end
    end
  end

  def credit_card
    @credit_card ||= ActiveMerchant::Billing::CreditCard.new(
      type: card_type,
      number: card_number,
      verification_value: card_verification,
      month: card_expires_on.month,
      year: card_expires_on.year,
      first_name: first_name,
      last_name: last_name
    )
  end
end

app/models/card_transaction.rb
class CardTransaction < ApplicationRecord
  belongs_to :card
  serialize :params

  def response= response
    self.success = response.success?
    self.authorization = response.authorization
    self.message = response.message
    self.params = response.params
  rescue ActiveMerchant::ActiveMerchantError => e
    self.success = false
    self.authorization = nil
    self.message = e.message
    self.params = {}
  end
end

app/models/category_review.rb
class CategoryReview < ApplicationRecord
  include CustomOrder
  has_many :reviews, dependent: :destroy

  validates :title, presence: true
end

app/models/category_tour.rb
class CategoryTour < ApplicationRecord
  has_many :tours, dependent: :destroy

  validates :title, presence: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  include CustomOrder
  belongs_to :user
  belongs_to :review

  validates :content, presence: true
end

app/models/images_tour.rb
class ImagesTour < ApplicationRecord
  belongs_to :tour

  has_attached_file :image, styles: {small: "64x64", med: "100x100", large: "200x200"}
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :review
end

app/models/overall_average.rb
class OverallAverage < ActiveRecord::Base
  belongs_to :rateable, :polymorphic => true
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, class_name: "User"
  belongs_to :rateable, polymorphic: true

  #attr_accessible :rate, :dimension

end

app/models/rating.rb
class Rating < ApplicationRecord
  belongs_to :user
  belongs_to :tour
end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

app/models/review.rb
class Review < ApplicationRecord
  include CustomOrder
  belongs_to :user
  belongs_to :category_review

  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  validates :title, presence: true, length: {maximum: 100}
  validates :content, presence: true

  has_attached_file :image, styles: {small: "64x64", med: "100x100", large: "300x300"}
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/tour.rb
class Tour < ApplicationRecord
  ratyrate_rateable "rating"
  belongs_to :category_tour

  has_many :book_tours
  has_many :ratings, dependent: :destroy
  has_many :images_tours, dependent: :destroy

  scope :recent, ->{order created_at: :desc}

  validates :name, presence: true, length: {maximum: 100}
  validates :schedule, presence: true
  validates :place_departure, presence: true
  validates :time, presence: true
  validates :people_number, presence: true
  validates :transport, presence: true
  validates :price, presence: true
  validates :content, presence: true
  validates :time_start, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  ratyrate_rater
  devise :database_authenticatable, :registerable,
    :rememberable, :validatable, :omniauthable, omniauth_providers: [:facebook]

  has_many :book_tours
  has_many :likes, dependent: :destroy
  has_many :activities, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :ratings, dependent: :destroy
  has_many :reviews, dependent: :destroy

  def likes? review
    review.likes.where(user_id: id).any?
  end

  class << self
    def from_omniauth access_token
      data = access_token.info
      user = User.find_by email: data["email"]
      unless user
        password = Devise.friendly_token[0,20]
        user = User.create name: data["name"], email: data["email"],
          password: password, password_confirmation: password
      end
      user
    end
  end
  mount_uploader :avatar, AvatarUploader

  scope :alphabet, ->{order :name}

  def is_user? user
    user == self
  end
end

app/controllers/tours_controller.rb
class ToursController < ApplicationController
  def index
    @categories = CategoryTour.all
    @q = Tour.search params[:q]
    @tours = @q.result.includes(:images_tours)
      .paginate page: params[:page], per_page: Settings.tour_pages
  end

  def show
    @tour = Tour.find_by id: params[:id]
    if @tour.nil?
      flash[:danger] = t "tour.not_found"
      redirect_to root_path
    else
      @images_tours = @tour.images_tours
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def logged_in?
    current_user.present?
  end

  def verify_admin
    unless current_user.is_admin?
      redirect_to root_url
    end
  end
end

app/views/tours/_tour.html.erb
<div class="col-md-4 project">
  <div class="projectThumbnail">
    <%= image_tag "g1.jpg", class: "img-responsive thumbnailImage" %>
  </div>
  <div class="projectInfo">
    <div class="clearfix"> </div>
    <h4><%= link_to tour.name, tour %></h4>
    <h4><%= number_to_currency tour.price %></h4>
    <p><%= tour.schedule %></p>
  </div>
</div>

app/views/tours/index.html.erb
<div class="gallery">
  <div class="container">
    <div class="galley-grid wow bounceInLeft" data-wow-delay="0.3s">
      <h1><%= t "tour.list" %></h1>
      <span class="lft-bar-gallery"> </span>
      <span class="rit-bar-gallery"> </span>
    </div>
    <div>
      <%= search_form_for @q, method: :get do |f| %>
        <div class="row">
          <div class="col-md-4">
            <%= f.select :category_tour_id_eq,
              options_from_collection_for_select(@categories, :id, :title),
              include_blank: t("all"), class: "form-control" %>
          </div>
          <div class="col-md-5">
            <%= f.search_field :name_or_schedule_cont,
            class: "form-control" %>
          </div>
          <div class="col-md-2">
            <%= f.submit t(:filter), class: "btn btn-primary" %>
          </div>
        </div>
      <% end %>
    </div>
    <hr/>
    <% if @tours.any? %>
      <div class="project-top wow fadeInUp animated" data-wow-delay=".5s">
        <%= render @tours %>
        <div class="clearfix"> </div>
        <div class="text-center">
          <%= will_paginate %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/tours/show.html.erb
<title><%= @tour.name %></title>
<div class="single">
  <div class="container">
  <div id="myCarousel" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
      <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
      <li data-target="#myCarousel" data-slide-to="1"></li>
      <li data-target="#myCarousel" data-slide-to="2"></li>
      <li data-target="#myCarousel" data-slide-to="3"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
      <div class="item active">
        <%= image_tag "01.jpg" %>
      </div>
      <div class="item">
        <%= image_tag "01.jpg" %>
      </div>
    </div>
    <a class="left carousel-control" href="#myCarousel"
      role="button" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left" aria-hidden="true">
      </span>
    </a>
    <a class="right carousel-control" href="#myCarousel"
      role="button" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right" aria-hidden="true">
      </span>
    </a>
  </div>
    <div class="single-top wow bounceInLeft" data-wow-delay="0.3s">
      <div class="lone-line">
        <h4><%= @tour.name %></h4>
        <ul class="grid-blog">
          <li><span><i class="glyphicon glyphicon-time"> </i>
            <%= t "tour.time" %>
            <%= @tour.time %></span>
          </li>
          <li><span><i class="glyphicon glyphicon-plane"></i>
            <%= t "tour.transport" %>
            <%= @tour.transport %></span>
          </li>
          <li><span><i class="glyphicon glyphicon-home"></i>
            <%= t "tour.place_departure" %>
            <%= @tour.place_departure %></span>
          </li>
          <li><span><i class="glyphicon glyphicon-play-circle"></i>
            <%= t "tour.time_start" %>
            <%= @tour.time_start %></span>
          </li>
        </ul>
        <div class="pull-right">
          <%= link_to new_book_tour_path(tour_id: @tour.id),
            class: "btn btn-primary" do %>
            <span class="glyphicon glyphicon-shopping-cart"></span>
            <%= t :Book_tour %>
          <% end %>
       </div>
        <h3><%= t "tour.schedule" %><%= @tour.schedule %></h3>
        <h2><%= t "tour.price" %><%= @tour.price.to_i %>
          <%= t "tour.usd" %>
        </h2>
        <p class="wow fadeInLeft animated" data-wow-delay=".5s">
          <%= @tour.content %>
        </p>
      </div>
    </div>
    <div class="small-2 large-4 columns">
      <% if current_user %>
        <%= t "rating" %>
        <%= rating_for @tour, "rating",
          disable_after_rate: true, imdb_avg: true %>
      <% end %>
    </div>
  </div>
</div>