config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  root "static_pages#home"
  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks#create"}
  mount Ckeditor::Engine => "/ckeditor"
  resources :reviews do
    resources :comments
    resource :like
  end
  namespace :admin do
    root "users#index", path: "/"
    resources :users, only: [:index, :show, :destroy]
  end
  resources :tours, only: [:index, :show]
  resources :book_tours
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize user
    user ||= User.new
    if user.is_admin?
      can :manage, :all
    else
      can :read, Tour
      can [:create, :update, :read], User
      can :manage, Review
    end
  end
end

app/models/activity.rb
class Activity < ApplicationRecord
  belongs_to :user

  validates :behavior, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/average_cache.rb
class AverageCache < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true
end

app/models/bank_account.rb
class BankAccount < ApplicationRecord
end

app/models/book_tour.rb
class BookTour < ApplicationRecord
  belongs_to :user
  belongs_to :tour

  has_one :card
  accepts_nested_attributes_for :card

  validates :people_number, presence: true

  def paypal_url(return_path)
    values = {
      business: Settings.business,
      cmd: "_xclick",
      upload: 1,
      return: "#{Rails.application.secrets.app_host}#{return_path}",
      invoice: id,
      amount: people_number * tour.price,
      quantity: "1",
      notify_url: "#{Rails.application.secrets.app_host}/update"
    }
   "#{Rails.application.secrets.paypal_host}/cgi-bin/webscr?" +
     values.to_query
  end
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :book_tour
  has_one :card_transaction

  attr_accessor :card_number, :card_verification

  before_create :validate_card

  def purchase
    response = GATEWAY.purchase price_in_cents, credit_card, purchase_options
    create_card_transaction(action: "purchase",
      amount: price_in_cents, response: response)
    book_tour.update_attribute(:purchased_at, Time.now) if response.success?
    response.success?
  end

  def price_in_cents
    (book_tour.people_number * book_tour.tour.price * 100).round
  end

  private

  def purchase_options
    {
      ip: ip_address,
      billing_address: {
        name: Settings.name,
        address1: Settings.address,
        city: Settings.city,
        state: Settings.state,
        country: Settings.country,
        zip: Settings.zip
      }
    }
  end

  def validate_card
    unless credit_card.valid?
      credit_card.errors.full_messages.each do |message|
        errors.add :base, message
      end
    end
  end

  def credit_card
    @credit_card ||= ActiveMerchant::Billing::CreditCard.new(
      type: card_type,
      number: card_number,
      verification_value: card_verification,
      month: card_expires_on.month,
      year: card_expires_on.year,
      first_name: first_name,
      last_name: last_name
    )
  end
end

app/models/card_transaction.rb
class CardTransaction < ApplicationRecord
  belongs_to :card
  serialize :params

  def response= response
    self.success = response.success?
    self.authorization = response.authorization
    self.message = response.message
    self.params = response.params
  rescue ActiveMerchant::ActiveMerchantError => e
    self.success = false
    self.authorization = nil
    self.message = e.message
    self.params = {}
  end
end

app/models/category_review.rb
class CategoryReview < ApplicationRecord
  include CustomOrder
  has_many :reviews, dependent: :destroy

  validates :title, presence: true
end

app/models/category_tour.rb
class CategoryTour < ApplicationRecord
  has_many :tours, dependent: :destroy

  validates :title, presence: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  include CustomOrder
  belongs_to :user
  belongs_to :review

  validates :content, presence: true
end

app/models/images_tour.rb
class ImagesTour < ApplicationRecord
  belongs_to :tour

  has_attached_file :image, styles: {small: "64x64", med: "100x100", large: "200x200"}
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :review
end

app/models/overall_average.rb
class OverallAverage < ActiveRecord::Base
  belongs_to :rateable, :polymorphic => true
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, class_name: "User"
  belongs_to :rateable, polymorphic: true

  #attr_accessible :rate, :dimension

end

app/models/rating.rb
class Rating < ApplicationRecord
  belongs_to :user
  belongs_to :tour
end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

app/models/review.rb
class Review < ApplicationRecord
  include CustomOrder
  belongs_to :user
  belongs_to :category_review

  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  validates :title, presence: true, length: {maximum: 100}
  validates :content, presence: true

  has_attached_file :image, styles: {small: "64x64", med: "100x100", large: "300x300"}
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/tour.rb
class Tour < ApplicationRecord
  ratyrate_rateable "rating"
  belongs_to :category_tour

  has_many :book_tours
  has_many :ratings, dependent: :destroy
  has_many :images_tours, dependent: :destroy

  scope :recent, ->{order created_at: :desc}

  validates :name, presence: true, length: {maximum: 100}
  validates :schedule, presence: true
  validates :place_departure, presence: true
  validates :time, presence: true
  validates :people_number, presence: true
  validates :transport, presence: true
  validates :price, presence: true
  validates :content, presence: true
  validates :time_start, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  ratyrate_rater
  devise :database_authenticatable, :registerable,
    :rememberable, :validatable, :omniauthable, omniauth_providers: [:facebook]

  has_many :book_tours
  has_many :likes, dependent: :destroy
  has_many :activities, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :ratings, dependent: :destroy
  has_many :reviews, dependent: :destroy

  def likes? review
    review.likes.where(user_id: id).any?
  end

  class << self
    def from_omniauth access_token
      data = access_token.info
      user = User.find_by email: data["email"]
      unless user
        password = Devise.friendly_token[0,20]
        user = User.create name: data["name"], email: data["email"],
          password: password, password_confirmation: password
      end
      user
    end
  end
  mount_uploader :avatar, AvatarUploader

  scope :alphabet, ->{order :name}

  def is_user? user
    user == self
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :load_review, except: [:new, :index, :create]
  before_action :load_category, only: [:edit, :new]

  def index
    @reviews = Review.latest.paginate page: params[:page],
      per_page: Settings.per_page
  end

  def show
    @comments = @review.comments.latest.paginate page: params[:page],
      per_page: Settings.per_page
  end

  def new
    @review = Review.new
  end

  def create
    @review = current_user.reviews.build review_params
    if @review.save
      flash[:success] = t "review.create_successfull"
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @review.update_attributes review_params
      flash[:success] = t "review.update_successfull"
      redirect_to reviews_path
    else
      flash[:notice] = t "review.update_error"
      render :edit
    end
  end

  def destroy
    if @review.destroy
      flash[:success] = t "review.delete_successfull"
    else
      flash[:notice] = t "review.delete_error"
    end
    redirect_to reviews_path
  end

  private
  def review_params
    params.require(:review).permit :title, :content, :images, :category_review_id
  end

  def load_review
    @review = Review.find_by id: params[:id]
    unless @review
      flash[:danger] = t "review.not_found"
      redirect_to root_path
    end
  end

  def load_category
    @categories = CategoryReview.sort_by_title
  end
end

app/views/reviews/_form.html.erb
<%= form_for @review do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :content %>
    <div class="col-sm-8">
    <%= f.cktext_area :content, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :category_review %>
    <%= f.collection_select :category_review_id, @categories, :id, :title %>
  </div>
  <%= f.submit t("submit"), class: "btn btn-default" %>
  </div>
<% end %>

app/views/reviews/_likes.html.erb
<% if user_signed_in? && current_user.likes?(@review) %>
  <%= link_to t("unlike"), review_like_path(@review), method: :delete, remote: true,
    class: "btn btn-primary" %>
<% else %>
  <%= link_to t("like"), review_like_path(@review), method: :post, remote: true,
    class: "btn btn-primary" %>
<% end %>

<%= @review.likes.count %>

<% @review.likes.each do |like| %>
  <%= like.user.name %>
<% end %>

app/views/reviews/_review.html.erb
<div class="col-md-4 project">
  <div class="projectThumbnail">
    <%= image_tag "g1.jpg", class: "img-responsive thumbnailImage" %>
  </div>
  <div class="projectInfo">
    <div class="clearfix"> </div>
    <h4><%= link_to review.title, review %></h4>
    <h4><%= review.category_review.title %></h4>
    <p><%= review.user.name %> | <%= l review.created_at, format: :short %></p>
  </div>
</div>

app/views/reviews/edit.html.erb
<div>
  <h2><%= t "review.edit" %></h2>
  <%= render "form" %>
</div>

app/views/reviews/index.html.erb
<div class="gallery">
  <div class="container">
    <div class="galley-grid wow bounceInLeft" data-wow-delay="0.3s">
      <h1><%= t "review.list" %></h1>
      <span class="lft-bar-gallery"> </span>
      <span class="rit-bar-gallery"> </span>
    </div>
    <hr/>
    <% if @reviews.any? %>
      <div class="project-top wow fadeInUp animated" data-wow-delay=".5s">
        <%= render @reviews %>
        <div class="clearfix"> </div>
        <div class="text-center">
          <%= will_paginate %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/reviews/new.html.erb
<div>
  <h2><%= t "review.create" %></h2>
  <%= render "form" %>
</div>

app/views/reviews/show.html.erb
<div class="single">
  <div class="container">
    <div class="single-top wow bounceInLeft" data-wow-delay="0.3s">
      <img class="img-responsive wow fadeInUp animated" data-wow-delay=".5s" src="images/b1.jpg" alt="" />
      <div class="lone-line">
        <h2 class="center"><%= @review.title %></h2>
        <ul class="grid-blog">
          <li><span><i class="glyphicon glyphicon-time"> </i>
            <%= l @review.created_at, format: :short %></span></li>
          <li><i class="glyphicon glyphicon-comment">
            </i><%= pluralize @review.comments.count, "comment" %></li>
          <li><a href="#"><i class="glyphicon glyphicon-user">
            </i><%= @review.user.name %></a></li>
        </ul>
        <p class="wow fadeInLeft animated" data-wow-delay=".5s">
          <%= raw @review.content %>
        </p>
        <% if user_signed_in? && @review.user_id == current_user.id %>
          <div class="center">
            <%= link_to t("edit"), edit_review_path(@review), class: "btn btn-default" %>
            <%= link_to t("delete"), review_path(@review), class: "btn btn-default",
              method: :delete, data: {confirm: t("confirm_delete")} %>
          </div>
        <% end %>
      </div>
    </div>
    <div id="review_<%= @review.id %>_likes">
      <%= render "likes", locals: {review: @review} %>
    </div>
    <div id="comment-form">
      <%= render "comments/form" %>
    </div>
    <h3><%= t "comment.title" %></h3>
    <div id="comments-list">
      <%= render @comments %>
      <%= will_paginate @comments %>
    </div>
  </div>
</div>