config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  root "static_pages#home"
  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks#create"}
  mount Ckeditor::Engine => "/ckeditor"
  resources :reviews do
    resources :comments
    resource :like
  end
  namespace :admin do
    root "users#index", path: "/"
    resources :users, only: [:index, :show, :destroy]
  end
  resources :tours, only: [:index, :show]
  resources :book_tours
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize user
    user ||= User.new
    if user.is_admin?
      can :manage, :all
    else
      can :read, Tour
      can [:create, :update, :read], User
      can :manage, Review
    end
  end
end

app/models/activity.rb
class Activity < ApplicationRecord
  belongs_to :user

  validates :behavior, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/average_cache.rb
class AverageCache < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true
end

app/models/bank_account.rb
class BankAccount < ApplicationRecord
end

app/models/book_tour.rb
class BookTour < ApplicationRecord
  belongs_to :user
  belongs_to :tour

  has_one :card
  accepts_nested_attributes_for :card

  validates :people_number, presence: true

  def paypal_url(return_path)
    values = {
      business: Settings.business,
      cmd: "_xclick",
      upload: 1,
      return: "#{Rails.application.secrets.app_host}#{return_path}",
      invoice: id,
      amount: people_number * tour.price,
      quantity: "1",
      notify_url: "#{Rails.application.secrets.app_host}/update"
    }
   "#{Rails.application.secrets.paypal_host}/cgi-bin/webscr?" +
     values.to_query
  end
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :book_tour
  has_one :card_transaction

  attr_accessor :card_number, :card_verification

  before_create :validate_card

  def purchase
    response = GATEWAY.purchase price_in_cents, credit_card, purchase_options
    create_card_transaction(action: "purchase",
      amount: price_in_cents, response: response)
    book_tour.update_attribute(:purchased_at, Time.now) if response.success?
    response.success?
  end

  def price_in_cents
    (book_tour.people_number * book_tour.tour.price * 100).round
  end

  private

  def purchase_options
    {
      ip: ip_address,
      billing_address: {
        name: Settings.name,
        address1: Settings.address,
        city: Settings.city,
        state: Settings.state,
        country: Settings.country,
        zip: Settings.zip
      }
    }
  end

  def validate_card
    unless credit_card.valid?
      credit_card.errors.full_messages.each do |message|
        errors.add :base, message
      end
    end
  end

  def credit_card
    @credit_card ||= ActiveMerchant::Billing::CreditCard.new(
      type: card_type,
      number: card_number,
      verification_value: card_verification,
      month: card_expires_on.month,
      year: card_expires_on.year,
      first_name: first_name,
      last_name: last_name
    )
  end
end

app/models/card_transaction.rb
class CardTransaction < ApplicationRecord
  belongs_to :card
  serialize :params

  def response= response
    self.success = response.success?
    self.authorization = response.authorization
    self.message = response.message
    self.params = response.params
  rescue ActiveMerchant::ActiveMerchantError => e
    self.success = false
    self.authorization = nil
    self.message = e.message
    self.params = {}
  end
end

app/models/category_review.rb
class CategoryReview < ApplicationRecord
  include CustomOrder
  has_many :reviews, dependent: :destroy

  validates :title, presence: true
end

app/models/category_tour.rb
class CategoryTour < ApplicationRecord
  has_many :tours, dependent: :destroy

  validates :title, presence: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  include CustomOrder
  belongs_to :user
  belongs_to :review

  validates :content, presence: true
end

app/models/images_tour.rb
class ImagesTour < ApplicationRecord
  belongs_to :tour

  has_attached_file :image, styles: {small: "64x64", med: "100x100", large: "200x200"}
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :review
end

app/models/overall_average.rb
class OverallAverage < ActiveRecord::Base
  belongs_to :rateable, :polymorphic => true
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, class_name: "User"
  belongs_to :rateable, polymorphic: true

  #attr_accessible :rate, :dimension

end

app/models/rating.rb
class Rating < ApplicationRecord
  belongs_to :user
  belongs_to :tour
end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

app/models/review.rb
class Review < ApplicationRecord
  include CustomOrder
  belongs_to :user
  belongs_to :category_review

  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  validates :title, presence: true, length: {maximum: 100}
  validates :content, presence: true

  has_attached_file :image, styles: {small: "64x64", med: "100x100", large: "300x300"}
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/tour.rb
class Tour < ApplicationRecord
  ratyrate_rateable "rating"
  belongs_to :category_tour

  has_many :book_tours
  has_many :ratings, dependent: :destroy
  has_many :images_tours, dependent: :destroy

  scope :recent, ->{order created_at: :desc}

  validates :name, presence: true, length: {maximum: 100}
  validates :schedule, presence: true
  validates :place_departure, presence: true
  validates :time, presence: true
  validates :people_number, presence: true
  validates :transport, presence: true
  validates :price, presence: true
  validates :content, presence: true
  validates :time_start, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  ratyrate_rater
  devise :database_authenticatable, :registerable,
    :rememberable, :validatable, :omniauthable, omniauth_providers: [:facebook]

  has_many :book_tours
  has_many :likes, dependent: :destroy
  has_many :activities, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :ratings, dependent: :destroy
  has_many :reviews, dependent: :destroy

  def likes? review
    review.likes.where(user_id: id).any?
  end

  class << self
    def from_omniauth access_token
      data = access_token.info
      user = User.find_by email: data["email"]
      unless user
        password = Devise.friendly_token[0,20]
        user = User.create name: data["name"], email: data["email"],
          password: password, password_confirmation: password
      end
      user
    end
  end
  mount_uploader :avatar, AvatarUploader

  scope :alphabet, ->{order :name}

  def is_user? user
    user == self
  end
end

app/views/layouts/_footer.html.erb
<div class="copy-right wow bounceInLeft" data-wow-delay="0.3s">
  <h3><%= t "framgia_book_tour" %></h3>
</div>

app/views/layouts/_footer_admin.html.erb
<div class="copy-right wow bounceInLeft" data-wow-delay="0.3s">
  <h3><%= t "framgia_book_tour" %></h3>
</div>

app/views/layouts/_header.html.erb
<div class="header">
  <div class="container">
    <div class="header-main">
      <div class="logo wow bounceInLeft" data-wow-delay="0.3s">
        <%= link_to image_tag("logo1.png"), root_path %>
      </div>
      <div class="top-navg">
        <span class="menu"><%= image_tag "icon.png" %></span>
        <nav class="cl-effect-13">
          <ul class="res">
            <li><%= link_to t("home"), root_path, class: "active" %></li>
            <li><%= link_to t("tour.tour"), tours_path %></li>
            <li><%= link_to t("review.title"), reviews_path %></li>
            <li class="dropdown">
              <%= link_to "#", {class: "dropdown-toggle",
                "data-toggle": "dropdown"} do %>
                <%= t "service" %>
                <b class="caret"></b>
              <% end %>
              <ul class="dropdown-menu background" role="menu">
                <li><%= link_to t("food"), "#" %></li>
                <li><%= link_to t("hotel"), "#" %></li>
                <li><%= link_to t("new"), "#" %></li>
              </ul>
            </li>
            <% if user_signed_in? %>
              <% if current_user.is_admin? %>
                <li><%= link_to t("admin.title"), admin_path %></li>
              <% end %>
                <li><%= link_to t("sign_out"), destroy_user_session_path,
                  method: :delete %></li>
            <% else %>
              <li><%= link_to t("sign_in"), new_user_session_path %></li>
              <li><%= link_to t("sign_up"), new_user_registration_path %></li>
            <% end %>
          </ul>
        </nav>
      </div>
    <div class="clearfix"></div>
    </div>
  </div>
</div>

app/views/layouts/_header_admin.html.erb
<div class="header">
  <div class="container">
    <div class="header-main">
      <div class="logo wow bounceInLeft" data-wow-delay="0.3s">
        <%= link_to image_tag("logo1.png"), "#" %>
      </div>
      <div class="top-navg">
        <span class="menu"><%= image_tag "icon.png" %></span>
        <nav class="cl-effect-13">
          <ul class="res">
            <li><%= link_to t("admin.user.home"), admin_path,
              class: "active" %></li>
            <li class="dropdown">
              <%= link_to "#", {class: "dropdown-toggle",
                "data-toggle": "dropdown"} do %>
                <%= t "admin.manager.title" %>
                <b class="caret"></b>
              <% end %>
              <ul class="dropdown-menu background">
                <li><%= link_to t("admin.manager.tour"), "#" %></li>
                <li><%= link_to t("admin.manager.category"), "#" %></li>
                <li><%= link_to t("admin.manager.review"), "#" %></li>
              </ul>
            </li>
            <li><%= link_to t("sign_out"), destroy_user_session_path,
                method: :delete %></li>
          </ul>
        </nav>
      </div>
    <div class="clearfix"></div>
    </div>
  </div>
</div>

app/views/layouts/_sidebar_admin.html.erb
<div id="section-navigation">
 <ul class="navi">
   <li><%= link_to t("sidebar.menu"), "#" %></li>
   <li><%= link_to t("sidebar.menu"), "#" %></li>
   <li><%= link_to t("sidebar.menu"), "#" %></li>
   <li><%= link_to t("sidebar.menu"), "#" %></li>
   <li><%= link_to t("sidebar.menu"), "#" %></li>
   <li><%= link_to t("sidebar.menu"), "#" %></li>
   <li><%= link_to t("sidebar.menu"), "#" %></li>
   <li><%= link_to t("sidebar.menu"), "#" %></li>
   <li><%= link_to t("sidebar.menu"), "#" %></li>
   <li><%= link_to t("sidebar.menu"), "#" %></li>
 </ul>
</div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= t "admin" %></title>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": true %>
    <%= javascript_include_tag "application", "data-turbolinks-track": true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render "layouts/header_admin" %>
    <div id="container">
        <h2 class="word-list">
        <%= yield %>
    </div>
    <%= render "layouts/footer_admin" %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= t "framgia_book_tour" %></title>
    <%= stylesheet_link_tag "application", media: "all",
      "data-turbolinks-track": true %>
    <%= javascript_include_tag "application", "data-turbolinks-track": true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
  <div class="container">
    <%= render "layouts/header" %>
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>">
        <%= value %>
      </div>
    <% end %>
    <%= yield %>
    <%= render "layouts/footer" %>
  </div>
  </body>
</html>